In [4]:
# 训练数据预处理
!python attr_data_preprocess.py

preprocess fine data
2866it [00:03, 730.24it/s]^C
2936it [00:04, 728.01it/s]
Traceback (most recent call last):
  File "attr_data_preprocess.py", line 109, in <module>
    rets.append(json.dumps(data, ensure_ascii=False) + "\n")
  File "/home/haoquan/miniconda3/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/haoquan/miniconda3/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/haoquan/miniconda3/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
KeyboardInterrupt


In [ ]:
# 生成关系字典
!python attr_generate_attr_relation_dict.py

In [5]:
# 测试数据预处理
!python attr_test_data_preprocess.py

preprocess test data
4000it [00:05, 697.31it/s]
4000


In [10]:
# 属性训练
!sh train_kfold_cat_attr_matching.sh

Trian folds [0, 1] 

89588it [00:40, 2187.00it/s]
50000it [00:24, 2041.65it/s]
2022-05-23 11:09:30,588 - INFO: Begin train fold 0
2022-05-23 11:09:30,596 - INFO: train_data len 125629
2022-05-23 11:09:30,596 - INFO: val_data len 13959
model param num 12767233
2022-05-23 11:09:48,122 - INFO: Epoch:[0|60], Acc:83.46%, LR:1.67e-04
2022-05-23 11:09:49,492 - INFO: Epoch:[0|60], Acc:87.31%, LR:1.67e-04
2022-05-23 11:09:50,873 - INFO: Epoch:[0|60], Acc:88.66%, LR:1.67e-04
2022-05-23 11:09:52,331 - INFO: Epoch:[0|60], Acc:88.88%, LR:1.67e-04
2022-05-23 11:09:53,856 - INFO: Epoch:[0|60], Acc:89.56%, LR:1.67e-04
2022-05-23 11:09:55,458 - INFO: Epoch:[0|60], Acc:89.54%, LR:1.67e-04
2022-05-23 11:09:57,054 - INFO: Epoch:[0|60], Acc:89.62%, LR:1.67e-04
2022-05-23 11:09:58,593 - INFO: Epoch:[0|60], Acc:90.01%, LR:1.67e-04
2022-05-23 11:10:00,115 - INFO: Epoch:[0|60], Acc:90.09%, LR:1.67e-04
2022-05-23 11:10:01,592 - INFO: Epoch:[0|60], Acc:90.10%, LR:1.67e-04
100%|███████████████████████████████████

In [12]:
!python test_kfold_attr_matching.py --gpu 0 --fold_num 2

loss
model num 2
4000it [00:15, 257.67it/s]
pos_num: 4463


In [10]:
import numpy as np
cat_res = [
    [0.936623235543569, 0.1612488180398941],
    [0.9366423288981119, 0.16067825257778168],
    [0.9369659622510275, 0.16053123772144318],
    [0.9376933574676514, 0.1604292243719101],
    [0.9363299608230591, 0.1594846546649933],
    [0.9372080167134603, 0.15893949568271637],
    [0.9345680276552836, 0.16276989877223969],
    [0.9361033837000529, 0.1607181876897812],
    [0.9365274310112, 0.1590977907180786],
    [0.9363700350125631, 0.16256952285766602],
]
cat_res = np.array(cat_res)
cat_res_loss = cat_res[:, 1]
np.argsort(cat_res_loss), np.mean(cat_res[:,1]), np.mean(cat_res[:,0])

(array([5, 8, 4, 3, 2, 1, 7, 0, 9, 6]), 0.16064670830965042, 0.936503173907598)

In [6]:
se_res = [
    [0.9371674855550131, 0.15867383778095245],
    [0.936972975730896, 0.1593627780675888],
    [0.9374750852584839, 0.15870358049869537],
    [0.9382347663243612, 0.15816082060337067],
    [0.9360637863477071, 0.1578788161277771],
    [0.9384589989980062, 0.15506406128406525],
    [0.9346340298652649, 0.16176994144916534],
    [0.9372538725535074, 0.1587478369474411],
    [0.9374122222264608, 0.15836788713932037],
    [0.9369425972302755, 0.15741004049777985],
]
se_res = np.array(se_res)
se_res_loss = se_res[:, 1]
np.argsort(se_res_loss), np.mean(se_res_loss), np.mean(se_res[:, 0])

(array([5, 9, 4, 3, 8, 0, 2, 7, 1, 6]),
 0.15841396003961564,
 0.9370615820089977)

In [7]:
import numpy as np
cat_res = [
    [0.936623235543569, 0.1612488180398941],
    [0.9366533358891805, 0.1624182015657425],
    [0.9366117715835571, 0.15966655313968658],
    [0.9373950362205505, 0.1600065976381302],
    [0.9358641505241394, 0.1602543741464615],
    [0.9375622868537903, 0.1589227318763733],
    [0.933951755364736, 0.1641961932182312],
    [0.9362029234568278, 0.16201548278331757],
    [0.9359965324401855, 0.15938925743103027],
    [0.937735358874003, 0.16180814802646637],
]
cat_res = np.array(cat_res)
cat_res_loss = cat_res[:, 1]
np.argsort(cat_res_loss), np.mean(cat_res[:,1]), np.mean(cat_res[:,0])

(array([5, 8, 2, 3, 4, 0, 9, 7, 1, 6]), 0.16099263578653336, 0.936459638675054)

In [11]:
se_res = [
    [0.9371674855550131, 0.15867383778095245],
    [0.9373257160186768, 0.15898078680038452],
    [0.9372979998588562, 0.15806789696216583],
    [0.9378480513890585, 0.1569475680589676],
    [0.9371063113212585, 0.1576402485370636],
    [0.9380383094151815, 0.15499703586101532],
    [0.934656043847402, 0.15733158588409424],
    [0.9369109471638998, 0.1587478369474411],
    [0.9366490642229716, 0.1584760695695877],
    [0.9371958374977112, 0.15901808440685272],
]
se_res = np.array(se_res)
se_res_loss = se_res[:, 1]
np.argsort(se_res_loss), np.mean(se_res_loss), np.mean(se_res[:, 0])

(array([5, 3, 6, 4, 2, 8, 0, 7, 1, 9]), 0.1578880950808525, 0.9370195766290029)

In [9]:
import numpy as np
cat_res = [
    [0.9372231960296631, 0.1587768793106079],
    [0.9362248380978903, 0.1617080420255661],
    [0.9358292818069458, 0.1636129766702652],
    [0.9368566274642944, 0.16079123318195343],
    [0.9361645181973776, 0.15938310325145721],
    [0.9376281897226969, 0.1554555892944336],
    [0.9376836617787679, 0.1641961932182312],
    [0.9357333381970724, 0.1603342741727829],
    [0.9351005156834921, 0.1624642163515091],
    [0.93595423301061, 0.16189731657505035],
]
cat_res = np.array(cat_res)
cat_res_loss = cat_res[:, 1]
np.argsort(cat_res_loss), np.mean(cat_res[:,1]), np.mean(cat_res[:,0])

(array([5, 0, 4, 7, 3, 1, 9, 8, 2, 6]), 0.1608619824051857, 0.9364398399988811)

In [2]:
from model.attr_mlp import (
    FinalCatModel,
    FinalSeAttrIdMatch,
)

model = FinalCatModel(attr_num=80)
print("param num", sum(param.numel() for param in model.parameters()))

model = FinalSeAttrIdMatch(attr_num=80)
print("param num", sum(param.numel() for param in model.parameters()))

param num 12767233
param num 21159937


In [3]:
(21159937+12767233)*5

169635850

In [22]:
import numpy as np
np.random.seed(0)
import random
random.seed(0)
random.random()

0.8444218515250481

In [9]:
import random
random.random()

0.3294313382419294

In [ ]:
from torch.utils.data import Dataset, DataLoader


class AttrIdMatchDataset(Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        item = self.data[idx]
        res = random.sample(item, 1)[0]
        return res

data = np.arange(10)